annotations_root: ../../../hd-epic-annotations
intermediate_root: Intermediate_data

inputs:
  videos:
    - P01-20240203-132119

# Sampling
sampling_fps: 1.0
fps_for_frame_lookup: 30.0

# Out-of-sight definition
out_of_sight_horizon_sec: 5.0
max_questions_per_video: 30

# step 2 last visible observation
raw_video_width: 1408
raw_video_height: 1408

# last placement observation
last_placement_source: raw_tracks
#or merged tracks (accuracy depends on frame sampling rate)


# Step 3 (fixture)
absolute:
  num_choices: 5

# Step 4 (object-object relation)
relative:
  border_tolerance_deg: 10.0

# step 5 (object-object distance)

# General
random_seed: 42

# Output
output_json: outputs/generated_vqa/P01-20240203-132119_vqa_visible_30.json

#in_view track
visibility_tracks_json:
  P01-20240203-132119: outputs/merged_tracks/P01/P01-20240203-132119_merged_visibility_track.json

