annotations_root: ../../../hd-epic-annotations
intermediate_root: Intermediate_data

inputs:
  videos:
    - P01-20240203-184045

# Sampling
sampling_fps: 2.0
fps_for_frame_lookup: 30.0
pre_context_sec: 0.5

# Out-of-sight definition
out_of_sight_horizon_sec: 1.0
max_questions_per_video: 5

# step 2 last visible observation
raw_video_width: 1408
raw_video_height: 1408

# last placement observation
last_placement_source: merged_tracks #raw_tracks
#or merged tracks (accuracy depends on frame sampling rate)


# Step 3 (fixture)
absolute:
  num_choices:  3

# Step 4 (object-object relation)
relative:
  border_tolerance_deg: 10.0

# step 5 (object-object distance)

# General
random_seed: 42

# Output
output_json: outputs/generated_vqa/P01-20240203-184045_vqa.json

#in_view track
visibility_tracks_json:
  P01-20240203-184045: outputs/merged_tracks/P01/P01-20240203-184045_merged_visibility_track.json

