# EREN SETUP: data_root: ../../../../HD-EPIC
# IVO SETUP: data_root: ../../../../data
#
#
annotations_root: ../../../../hd-epic-annotations
data_root: ../../../../HD-EPIC
intermediate_data_root: ../../../../hd-epic-annotations/Intermediate_data

inputs:
  participants: [P01]
  videos: [P01-20240202-161354]

sampling_fps: 2.0
out_of_sight_horizon_sec: 2.0
max_questions_per_video: 20

question_classes:
  absolute: true
  relative: true

relative:
  border_tolerance_deg: 10.0

absolute:
  num_choices: 5

output_json: ../../outputs/oos_location_recall_questions.json
random_seed: 42
